version: '3.8'

services:
  svm_service:
    build:
      context: ./svm_service/svm_service
    ports:
      - "8501:8501"
    container_name: svm_service

  vgg_service:
    build:
      context: ./vgg_service/vgg_service
    ports:
      - "8502:8501" 
    container_name: vgg_service
